apiVersion: v1
kind: Pod
metadata:
  name: demo-kotlinapp
  labels:
    app: webapp
spec:
  containers:
    - name: web
      image: tongtongshi/test:latest
      ports:
        - containerPort: 80
          name: web
          protocol: TCP
